sudo: required
language: cpp
services:
  - docker

before_install:
  - docker pull ubuntu:latest
  - docker run -itd --name build -v $(pwd):/repo ubuntu:latest sh           
  - docker exec build apt-get -qq update
  - docker exec build apt-get install -y build-essential apt-utils git automake autoconf libtool  dovecot-core dovecot-dev librados-dev  

script:
  - docker exec build sh -c 'cd repo; ./autogen.sh'
  - docker exec build sh -c 'cd repo; ./configure --with-dovecot=/usr/lib/dovecot --enable-maintainer-mode --enable-debug'
  - docker exec build sh -c 'cd repo; make'
